name: Lint Code Base

on:
  workflow_call:
    inputs:
      pylint-args:
        required: false
        type: string
        default: ""
      dirs:
        required: false
        type: string
        default: "**/*.py"
      requirements-file:
        required: false
        type: string
        default: "requirements.txt"
      python-version:
        required: false
        type: string
        default: "3.10.*"
jobs:
  prepare-python:
    name: Install python requirements
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install requirements
        run: pip install pylint black isort && pip install -r ${{ inputs.requirements-file }}

  pylint:
    name: Run pylint checks
    runs-on: ubuntu-latest
    needs: prepare-python
    steps:
      - run: pylint ${{ inputs.pylint-args }} ${{ inputs.dirs }}

  black:
    name: Run black checks
    runs-on: ubuntu-latest
    needs: prepare-python
    steps:
      - run: black --check ${{ inputs.dirs }}

  isort:
    name: Run isort checks
    runs-on: ubuntu-latest
    needs: prepare-python
    steps:
      - run: isort --check ${{ inputs.dirs }}
