name: Lint Code Base

on:
  workflow_call:
    inputs:
      pylint-args:
        required: false
        type: string
        default: ""
      dirs:
        required: false
        type: string
        default: ${{ github.workspace }}
      requirements-file:
        required: false
        type: string
        default: "requirements.txt"
      python-version:
        required: false
        type: string
        default: "3.10.*"
jobs:
  python-linters:
    name: Check python code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python ${{ inputs.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install requirements from ${{ inputs.requirements-file }}
        run: pip install pylint black isort && pip install -r ${{ inputs.requirements-file }}

      - run: ls -la

      - name: Run pylint checks
        run: pylint ${{ inputs.pylint-args }} ${{ inputs.dirs }}

      - name: Run black checks
        run: black --check ${{ inputs.dirs }}

      - name: Run isort checks
        run: isort --check ${{ inputs.dirs }}
