name: Lint Code Base

on: workflow_call

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10

      - name: Install requirements
        run: pip install pylint && pip install -r requirements.txt

      - name: Run pylint checks
        run: pylint ./
